# Generated by Django 4.2.8 on 2023-12-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CynerioTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_task', max_length=100)),
                ('is_checkin', models.BooleanField(default=False)),
                ('started', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
